import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.util.Objects;
import java.util.Vector;

public class Main{
	static final JFrame frame=new JFrame();
	static final JTextArea width=new JTextArea("width"),height=new JTextArea("height"),mines=new JTextArea("number of mines");
	static final JButton reset=new JButton();
	static void gamePaint(){if(game.ended)game.run();}
	static final AbstractAction[]actions={new AbstractAction(){@Override public void actionPerformed(ActionEvent e){if(game.Y>0)game.Y--;gamePaint();}},new AbstractAction(){@Override public void actionPerformed(ActionEvent e){if(game.X>0)game.X--;gamePaint();}},new AbstractAction(){@Override public void actionPerformed(ActionEvent e){if(game.Y+game.gameHeight<game.height)game.Y++;gamePaint();}},new AbstractAction(){@Override public void actionPerformed(ActionEvent e){if(game.X+game.gameWidth<game.width)game.X++;gamePaint();}},new AbstractAction(){@Override public void actionPerformed(ActionEvent e){if(game.Y-50>0)game.Y-=50;else game.Y=0;gamePaint();}},new AbstractAction(){@Override public void actionPerformed(ActionEvent e){if(game.X-50>0)game.X-=50;else game.X=0;gamePaint();}},new AbstractAction(){@Override public void actionPerformed(ActionEvent e){if(game.Y+game.gameHeight+50<game.height)game.Y+=50;else game.Y=game.height-game.gameHeight;gamePaint();}},new AbstractAction(){@Override public void actionPerformed(ActionEvent e){if(game.X+game.gameWidth+50<game.width)game.X+=50;else game.X=game.width-game.gameWidth;gamePaint();}},new AbstractAction(){@Override public void actionPerformed(ActionEvent e){game.Y=0;gamePaint();}},new AbstractAction(){@Override public void actionPerformed(ActionEvent e){game.X=0;gamePaint();}},new AbstractAction(){@Override public void actionPerformed(ActionEvent e){game.Y=game.height-game.gameHeight;gamePaint();}},new AbstractAction(){@Override public void actionPerformed(ActionEvent e){game.X=game.width-game.gameWidth;gamePaint();}}};
	//TODO static JButton[]directions=new JButton[12];
	static BufferedImage ss10,ss40;
	static final Vector<Image>ss10img=new Vector<>(),ss40img=new Vector<>();
	static final JLabel location=new JLabel(),minesLeft=new JLabel();
	static boolean flag;
	static final Color back=new Color(0x171717),fore=new Color(0xb0b0b0);
	static final Border border=new LineBorder(fore,1);
	static flag flagButton;
	static check check;
	static game game;
	public static void main(String[] args) throws Exception{
		ss10=ImageIO.read(Objects.requireNonNull(Main.class.getResource("ss10.png")));
		ss40=ImageIO.read(Objects.requireNonNull(Main.class.getResource("ss40.png")));
		for(int y=0;y<3;y++)for(int x=0;x<4;x++)ss10img.add(ss10.getSubimage(x*10,y*10,10,10));
		for(int y=0;y<2;y++)for(int x=0;x<3;x++)ss40img.add(ss40.getSubimage(x*40,y*40,40,40));
		ss40img.remove(ss40img.size()-1);
		flagButton=new flag();
		check=new check();
		game=new game();
		game.setBorder(border);
		width.setBackground(Color.black);
		width.setForeground(fore);
		width.setBorder(border);
		width.setBounds(95,5,101,21);
		width.setCaretColor(fore);
		height.setBackground(Color.black);
		height.setForeground(fore);
		height.setBorder(border);
		height.setBounds(195,5,100,21);
		height.setCaretColor(fore);
		mines.setBackground(Color.black);
		mines.setForeground(fore);
		mines.setBorder(border);
		mines.setBounds(95,25,101,20);
		mines.setCaretColor(fore);
		reset.setBackground(new Color(0x303030));
		reset.setForeground(fore);
		reset.setBorder(border);
		reset.setBounds(195,25,100,20);
		reset.setText("reset");
		reset.setFocusable(false);
		location.setBackground(back);
		location.setForeground(fore);
		location.setBounds(300,25,400,20);
		minesLeft.setBackground(back);
		minesLeft.setForeground(fore);
		minesLeft.setBounds(300,5,400,20);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setLayout(null);
		frame.add(flagButton);
		frame.add(new check());
		frame.add(game);
		frame.add(width);
		frame.add(height);
		frame.add(mines);
		frame.add(reset);
		frame.add(location);
		frame.add(minesLeft);
		frame.getContentPane().setBackground(back);
		frame.setSize(game.getWidth()+25,game.getHeight()+95);
		frame.setResizable(false);
		frame.setVisible(true);
	}
}